default: &default
  name: Sample CSV Parser APP
  database:
    host: "localhost"
    port: "27017"
   # user: admin
   # password: "admin"
  csvFileName: "Category.csv"
  csvSubFileName: "SubCategory.csv"





development:
  <<: *default
  database:
    name: masterservice_dev

test:
  <<: *default
  database:
    name: masterservice_test